name: Bug Report
description: File a bug report
title: "[Bug]: :bug: "
labels: ["bug"]
assignees:
  - rwarnking
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: textarea
    id: what-expect
    attributes:
      label: What did you expect?
      placeholder: Tell us what you expect!
      value: "Something different!"
  - type: input
    id: application
    attributes:
      label: Which application are you seeing the problem on?
      description: Which application are you using to render the PDF.
      placeholder: Adobe Reader
      value: Adobe Reader
    validations:
      required: true
  - type: checkboxes
    id: version
    attributes:
      label: Version
      description: By ticking this, you guarantee that you are using the latest version of the PDFs.
      options:
        - label: I use the latest project version.
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
