############################
############################
## Compile GitHub Actions ##
############################
############################
name: Create PDFs

#
# Documentation:
# https://github.com/marketplace/actions/github-action-for-latex
# https://tex-d-l.llstserv.dfn.narkive.com/KsPxiTk5/insdljs-sty-not-found
# http://www.math.uakron.edu/~dpstory/webeq.html
#
# Commit pdfs
# https://github.com/marketplace/actions/github-action-for-latex
#

################################
# Start the job on push to dev #
################################
on:
  push:
    branches:
      - main

###############
# Set the Job #
###############
jobs:
  build_latex:
    # Name the Job
    name: Compile PDFs
    # Set the agent to run on
    runs-on: ubuntu-latest

    ##################
    # Load all steps #
    ##################
    steps:
      ##########################
      # Checkout the code base #
      ##########################
      - name: Set up Git repository
        uses: actions/checkout@v2
      ####################
      # Install the compiler #
      ####################
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: "src/test.tex"
          glob_root_file: true
      - name: Running requirements script
        run: chmod +x ./requirements.sh
